Fixes
zippyvision/smart-id-ruby pull request #3
Opened 2023-06-14 15:38 UTC by 5andi5

2023-08-28 08:25 UTC, 5andi5 commented
@LeKristapino Could You review these changes, please?

2023-08-29 13:05 UTC, LeKristapino commented
@5andi5 Sorry, will review & merge

2023-08-29 13:07 UTC, 5andi5 commented
@LeKristapino Thanks a lot

2023-08-29 13:09 UTC, LeKristapino requested changes
@5andi5 Please remove the commented out code if it is not needed anymore.

2023-08-29 13:09 UTC, LeKristapino commented on lib/smart_id/api/request.rb
> +    # DEMO_SSL_KEY = "QLZIaH7Qx9Rjq3gyznQuNsvwMQb7maC5L4SLu/z5qNU="
I guess if this is not needed we can delete

2023-08-29 13:09 UTC, LeKristapino commented on lib/smart_id/api/request.rb
> +    # def maybe_warn_of_ssl_key_expiry
Same here

2023-08-29 16:04 UTC, 5andi5 commented
> @5andi5 Please remove the commented out code if it is not needed anymore.

@LeKristapino Issue fixed

2023-08-29 16:35 UTC, merged